export const onj = {
	collaborative: false,
	description: '',
	external_urls: {spotify: 'https://open.spotify.coHG'},
	href: 'https://api.spotifymv5NmCJa8IkEPHG',
	id: '5XDa8IkEPHG',
	images: [{height: 640, url: 'https://m010b4', width: 640}],
	name: 'WeRock',
	owner: {display_name: 'Jedi', external_urls: {}, href: 'https://a6brtpx5e0fsq', id: 'f6ne0fsq', type: 'user', uri: 'spotify:user:f'},
	primary_color: null,
	public: true,
	snapshot_id: 'NDAsNjY5MGY2MjIxMjNhNDg2ZDhkMjc4MmRiN2ZmNzdhYTczYzJjMGRmMQ==',
	tracks: {href: 'https://api.spotify.com/tracks', total: 21},
	type: 'playlist',
	uri: 'spotify:playlist:5XDzma8IkEPHG',
};
